# Generated by Django 4.0.2 on 2022-01-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta', '0002_rename_tarjeta_rtarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('identificacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('empleado', models.CharField(max_length=100)),
            ],
        ),
    ]
